# Taller modelos de regresión lineal regularizados

Con el archivo de datos suministrado, va a crear un modelo **lineal** que prediga la variable **Weight**.

Información sobre este archivo, incluido el diccionario de datos, la puede obtener en [Kaggle](https://www.kaggle.com/datasets/samruddhim/olympics-althlete-events-analysis).

In [50]:
from pathlib import Path
import pandas as pd

#aqui le decimos a python en que carpeta estan los datos
DATA_DIR = Path().resolve().parent / "data" / "raw"
data_file = "athlete_events.csv"
data_path = DATA_DIR / data_file
df = pd.read_csv(data_path) 
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

Haga un análisis exploratorio y descarte variables irrelevantes.

Elimine los registros duplicados.

Elimine datos nulos de la variable objetivo.

Impute a los datos nulos de la variable **Medal** la categoría **No medal**.

In [51]:
#Eliminar Games es variable redundante
df.drop(columns=["Games"], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Year    271116 non-null  int64
 9   Season  271116 non-null  object
 10  City    271116 non-null  object
 11  Sport   271116 non-null  object
 12  Event   271116 non-null  object
 13  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 29.0+ MB

In [52]:
df.describe()

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

In [53]:
#ID debe ser variable categorica
df['ID'] = df['ID'].astype('object')

**Variables deben descartarse**

- ID y Names son casi claves primaras no predicen la variable weight

- Team, Event, NOC, Sport y City tienen alta cardinalidad.Para procesarlar se usa targetEncoder

In [54]:
df = df.drop(columns=['ID', 'Name'])

In [55]:
df.describe(include="object").T

         count unique                      top    freq
Sex     271116      2                        M  196594
Team    271116   1184            United States   17847
NOC     271116    230                      USA   18853
Season  271116      2                   Summer  222552
City    271116     42                   London   22426
Sport   271116     66                Athletics   38624
Event   271116    765  Football Men's Football    5733
Medal    39783      3                     Gold   13372

In [56]:
#proporcion valores nulos %
df.isnull().sum()*100/len(df)

Sex        0.000000
Age        3.494445
Height    22.193821
Weight    23.191180
Team       0.000000
NOC        0.000000
Year       0.000000
Season     0.000000
City       0.000000
Sport      0.000000
Event      0.000000
Medal     85.326207
dtype: float64

In [57]:
#La variable objetivo tiene datos nulos; estos deben descartarse.
df.dropna(subset=['Weight'], inplace=True)

 En el caso de la variable **Medal**, se imputa los datos nulos el valor **No medal**.

In [58]:
df = df.fillna({'Medal': 'No medal'})
df.isnull().sum()*100 / len(df)
print(len(df))

208241

In [60]:
df['Medal'].value_counts()

Medal
No medal    175984
Gold         10167
Bronze       10148
Silver        9866
Name: count, dtype: int64

Al descartar los nulos de Weight, la proporcion de datos nulos de Height y Age son bajos entonces pueden descartarse

In [59]:
df.dropna(subset=['Age','Height'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 206165 entries, 0 to 271115
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Sex     206165 non-null  object
 1   Age     206165 non-null  float64
 2   Height  206165 non-null  float64
 3   Weight  206165 non-null  float64
 4   Team    206165 non-null  object
 5   NOC     206165 non-null  object
 6   Year    206165 non-null  int64
 7   Season  206165 non-null  object
 8   City    206165 non-null  object
 9   Sport   206165 non-null  object
 10  Event   206165 non-null  object
 11  Medal   206165 non-null  object
dtypes: float64(3), int64(1), object(8)
memory usage: 20.4+ MB

In [61]:
#Se eliminan duplicados
df = df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 205846 entries, 0 to 271115
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Sex     205846 non-null  object
 1   Age     205846 non-null  float64
 2   Height  205846 non-null  float64
 3   Weight  205846 non-null  float64
 4   Team    205846 non-null  object
 5   NOC     205846 non-null  object
 6   Year    205846 non-null  int64
 7   Season  205846 non-null  object
 8   City    205846 non-null  object
 9   Sport   205846 non-null  object
 10  Event   205846 non-null  object
 11  Medal   205846 non-null  object
dtypes: float64(3), int64(1), object(8)
memory usage: 20.4+ MB

## EDA

In [62]:
#Categorias de variables categoricas no descartadas
cat_vars = df.select_dtypes(include='object').columns
for var in cat_vars:
    print(f'{var}:\n {df[var].unique()} unique values \n')

Sex:
 ['M' 'F'] unique values

Team:
 ['China' 'Netherlands' 'United States' 'Finland' 'Norway' 'Romania'
 'Estonia' 'France' 'Spain' 'Egypt' 'Bulgaria' 'Italy' 'Azerbaijan'
 'Russia' 'Argentina' 'Cuba' 'Belarus' 'Greece' 'Cameroon' 'Mexico'
 'Soviet Union' 'Nicaragua' 'Hungary' 'Nigeria' 'Algeria' 'Kuwait'
 'Bahrain' 'Pakistan' 'Iraq' 'Lebanon' 'Qatar' 'Malaysia' 'Iran' 'Canada'
 'Ireland' 'Australia' 'South Africa' 'Morocco' 'Eritrea' 'Tanzania'
 'Jordan' 'Sudan' 'Tunisia' 'Libya' 'Belgium' 'Djibouti' 'Comoros'
 'Kazakhstan' 'Brunei' 'Saudi Arabia' 'Maldives' 'Ethiopia' 'Indonesia'
 'Philippines' 'Uzbekistan' 'United Arab Emirates' 'Kyrgyzstan'
 'Tajikistan' 'Unified Team' 'Japan' 'Japan-1' 'Brazil' 'West Germany'
 'East Germany' 'Germany' 'Israel' 'Sweden' 'United States Virgin Islands'
 'Turkey' 'Sri Lanka' 'Armenia' "Cote d'Ivoire" 'Kenya' 'Benin' 'France-1'
 'Ukraine' 'Ghana' 'Somalia' 'Latvia' 'Syria' 'Great Britain' 'Chile'
 'Switzerland' 'India' 'Poland' 'Costa Rica' 'Panama' 'Georgia' 'Slovenia'
 'Croatia' 'Russia-2' 'Russia-1' 'Guyana' 'Portugal' 'Angola' 'Venezuela'
 'Colombia' 'Bangladesh' 'Palestine' 'Peru' 'Uruguay' 'Puerto Rico'
 'Uganda' 'New Zealand' 'Switzerland-2' 'Switzerland-1' 'Honduras'
 'Ecuador' 'Turkmenistan' 'Mauritius' 'Czechoslovakia' 'Seychelles'
 'Great Britain-1' 'Mauritania' 'Czech Republic' 'Niger'
 'Saint Kitts and Nevis' 'Trinidad and Tobago' 'Dominican Republic'
 'Jamaica' 'Liberia' 'Suriname' 'Nepal' 'Mongolia' 'Germany-2' 'Palau'
 'Lithuania' 'Monaco' 'Togo' 'Namibia' 'Netherlands Antilles' 'Iceland'
 'American Samoa' 'Austria' 'Samoa' 'Rwanda' 'Dominica' 'Haiti' 'Denmark'
 'Malta' 'Luxembourg' 'United States-1' 'United States-2' 'Cyprus'
 'Guinea' 'Xolotl' 'El Salvador' 'Belize' 'Paraguay' 'Indonesia-1'
 'Germany-1' 'South Yemen' 'South Korea' 'Mutafo' 'Yeoman VII'
 'Yeoman XII' 'Singapore' 'Bermuda' 'Serbia and Montenegro' 'Sierra Leone'
 'Sweden-2' 'Papua New Guinea' 'Nigeria-2' 'Afghanistan' 'Yemen' 'Oman'
 'Individual Olympic Athletes' 'North Yemen' 'Fiji' 'France-2' 'Vanuatu'
 'Moldova' 'Canada-2' 'Canada-1' 'Yugoslavia' 'Bahamas' 'Guatemala'
 'Burevestnik' 'Druzhba' 'Soviet Union-2' 'Soviet Union-1' 'Olen' 'Serbia'
 'British Virgin Islands' 'Saint Vincent and the Grenadines'
 'Central African Republic' 'Madagascar' 'Malaya' 'Chad'
 'Bosnia and Herzegovina' 'Guam' 'Brazil-1' 'Cayman Islands' 'Slovakia'
 'Barbados' 'Spain-2' 'Guinea Bissau' 'Tajamar' 'Spain-1' 'Italy-1'
 'Italy-2' 'Puerto Rico-2' 'Thailand' 'Timor Leste' 'Gabon'
 'East Germany-1' 'San Marino' 'Laos' 'Botswana'
 'Refugee Olympic Athletes' 'Lett' 'North Korea' 'South Korea-2'
 'Brazil-2' 'Mozambique' 'Senegal' 'Cape Verde' 'Great Britain-2'
 'Yugoslavia-1' 'Germany-3' 'Romania-2' 'Bolivia' 'Sweden-1' 'Andorra'
 'Japan-2' 'Austria-1' 'Austria-2' 'Antigua and Barbuda' 'Canada-3'
 'Latvia-2' 'Australia-2' 'Greece-1' 'Greece-2' 'West Germany-2'
 'Zimbabwe' 'Grenada' 'Bulgaria-1' 'Hong Kong' 'Ciocca II' 'Mirtala'
 'Saint Lucia' 'Federated States of Micronesia' 'Myanmar' 'Evita VI'
 'Ukraine-2' 'Russia-3' 'Soviet Union-3' 'Malawi' 'Belarus-1'
 'United States-3' 'Bronia' 'Zambia' 'Congo (Kinshasa)' 'West Germany-1'
 'Rhodesia' 'East Germany-2' 'Mali' 'Chinese Taipei-1'
 'Sao Tome and Principe' 'Poland-1' 'Congo (Brazzaville)' 'Macedonia'
 'Australia-1' 'Tonga' 'Liechtenstein' 'Argentina-2' 'Equatorial Guinea'
 'Montenegro' 'London City Police-1' 'Firebird II' 'Czechoslovakia-1'
 'Czechoslovakia-2' 'Grifo III' 'Grifo IV' 'Bingo' 'Damoiselle IV'
 'Solomon Islands' 'Australasia' 'Unified Team-2' 'Mistral Hojris'
 'Cook Islands' 'Mauritius-2' 'Albania' 'Romania-1' 'Pampero' 'Symphony'
 'Sjhxa' 'Faneca' 'Ciocca III' 'Dinah V' 'Czech Republic-2' 'Nora'
 'Monica' 'Circus' 'Aletta' 'Widgeon' 'Czech Republic-1' 'Relampago'
 'Sirene' 'Snap' 'Snude' 'Tip' 'White Lady' 'Web II' 'Web III'
 'West Indies Federation' 'Posillipo III' 'Latvia-1' 'Monaco-1' 'Peri'
 'Tichiboo' 'Siames-Cat' 'Linglom' 'Swaziland' 'India-1' 'France-3'
 'Burkina Faso' 'Buraddoo' 'Burundi' 'Chok' 'Aruba' 'Puerto Rico-1'
 'Netherlands-2' 'Unified Team-1' 'Serendipity' 'Calcinhas' 'Chamukina'
 'Nausikaa 4' 'Nauru' 'Lucky Star' 'Briar' 'Netherlands-1' 'Gabbiano'
 'Gran Gesto' 'Rush IV' 'Ali-Baba II' 'Ali-Baba IV' 'Ali-Baba VI'
 'Ali-Baba IX' 'Indonesia-2' 'Pigoule' 'South Vietnam' 'Snowten III'
 'Libellule de Paris' 'Scram' 'Winnipeg Shamrocks-1' 'Peri II'
 'Fantasio III' 'Pousse-Moi Pas VII' 'China-2' 'China-1' 'Tango'
 'Argentina-1' 'Espuma del Mar' 'Monaco-2' 'Baccara' 'Elvis Va' 'Romolo'
 'Aldebaran II' 'Aldebaran' 'Galatea II' 'Twins VIII' 'Mari' 'Gambia'
 'Israel-1' 'Hong Kong-1' 'Malaysia-1' 'Chinese Taipei' 'Cambodia'
 'Chinese Taipei-2' 'Calimucho' 'Bhutan' 'Malaysia-2' 'KNS' 'Vietnam'
 'Poland-2' 'Venilia' 'Mauritius-1' 'SagaII' 'Gem' 'June Climene'
 'Cambria' 'Oleander XII' 'Phoenix' 'Ylliam VII' 'Tim-Tam III'
 'Ballerina IV' 'Calypse II' 'Ciocca' 'Galejan' 'Cuba-1'
 'Marshall Islands' 'Umberta V' 'Hungary-1' 'Akatonbo'
 'Studenternes Roklub-2' 'Rififi' 'New York Athletic Club #1-1'
 'Partenope' 'Bermudes' 'Kiribati' 'United States-7' 'Diablo' 'Beaver'
 'Meteor' 'Kurush IV' 'Vesania' 'Kurush II' 'Daisy' 'Acipactli'
 'Aphrodite' 'Frip IV' 'Mad Dog' 'Bulgaria-2' 'Bermudian' 'Ireland-2'
 'Naiad' 'Pakaria' 'Serbia-2' 'Paula' 'Oxalis' 'Joy' 'Thalatta'
 'Trintel II' 'Guanahani' 'Spirit III' 'Nigeria-1' 'Bella' 'May-Be 1960'
 'Inga-Lill XXXXIII' 'United Arab Republic' 'Mexico-1' 'Denmark-1'
 'Denmark-2' 'Tuvalu' 'Nirefs' 'Proteus II' 'rn-2' 'Pam' 'Oleander II'
 'Primorka' 'Cha-Cha III' 'Gem II' 'Gem III' 'Gem IV' 'Gem VII' 'Chaje II'
 '30. Februar' 'Cuba-2' 'Elisabeth X' 'Struten' 'Saar' 'East Germany-3'
 'Brigantia' 'Skum' 'Miss Denmark 1964' 'Newfoundland' 'Fram III' 'Mizar'
 'Miss Nippon V' 'Argeste' 'South Korea-1' 'Bajazzo' 'Tantalus'
 'Pan-Hellenic Athletic Club' 'Kosovo' 'Norway-2' 'Tlaloc' 'Springbok'
 'Viktoriya' 'Espardate' 'Belarus-2' 'Alain IV' 'Three Leaves'
 'Unified Team-3' 'Sheerio' 'Pasodoble' 'Kingfisher' 'Yangon' 'Roy'
 'Ukraine-1' 'Norway-1' 'Shrew II' 'Passaic Turnverein, Passaic'
 'Salamander' 'Slovakia-2' 'Jamaica-2' 'Andromeda' 'Viking' 'South Sudan'
 'Chicago Athletic Association' 'Sydney Rowing Club' 'Don Schufro' 'Syndi'
 'Miss Nippon IV' 'New Zealand-1'
 'Philadelphia Turngemeinde, Philadelphia' 'Lancet' 'West Germany-3'
 'Lesotho' 'Whisper' 'Balaton' 'Rika II' 'Kuling' 'Dylan-2' 'Minotaur'
 'Surprise' 'Australia-3' 'Boreas' 'MitaII' 'Slovakia-1' 'Bluebottle'
 'Clearwater' 'Singapore-2' 'Tu-Fri' 'New York Athletic Club-4'
 'Barco Deloro' 'Olimpia' 'Macky VI' 'Tengiri' 'Hayama' 'Rush VII'
 'Angelita' 'Yeoman' 'John B' 'Bim' 'Bonaparte' 'Toronto Argonauts'
 'North Korea-2' 'North Korea-1' 'Mythilus' 'Rambo' 'Floresco'
 'Hong Kong-2' 'Lucky' 'Spirit VI' 'Subbnboana' 'Slovenia-1'
 'United States Virgin Islands-1' 'Turnverein Vorwrts, Cleveland'
 'St. Louis Southwest Turnverein #2-3' 'Olympion' 'Leipzig' 'Red Indian'
 'Poland-3' 'Combine' 'Moseley Wanderers' 'Kathleen' 'Argo II' 'State VI'
 'Zefyros' 'Jest' 'Hungary-2' 'Slovenia-2' 'Riccar' 'Japan-3' 'Brentina'
 'Ireland-1' 'Uragan' 'Czechoslovakia-3' 'Bellatrix IX' 'Bellatrix XIII'
 'Glisten' 'Nadine' 'Grifone' 'Canopus' 'Twinkle' 'Rose Pompon' 'Lady C'
 'Persey' 'Wendehals' 'New York Athletic Club' 'Thailand-1' 'Pop Art'
 'Barrenjoey' 'Voloira II' 'Ylliam II' 'Ylliam VIII' 'Uzbekistan-2'
 'Bremen' 'Quando Quando' 'Union des Socits Franais de Sports Athletiques'
 'Tineke' 'Maryke' 'India-2' 'Falcon VI' 'Slaghoken II' 'Thailand-2'
 'Pandora' 'Rampage' 'Aretusa' 'Diabolo St Maurice' 'Ravel' 'Humbug V'
 'Tramontane' "Qu'Importe" 'Aloha II' 'Astrid III' 'Nokaut II' 'Almaz'
 'Tulilind' 'Tornado' 'Taifun' 'Notavel' 'Galopin De La Font'
 'Royal Club Nautique de Gand' 'Patricia' 'Kalayaan' "Ma'Lindo" 'Harmony'
 'Racing Club de France' 'Uzbekistan-1' 'Orion' 'Merope' 'Djinn'
 'Merope III' 'Amateur Athletic Association' 'Greenoaks Dundee'
 'Maid of Lebanon' 'Danaldo' 'Sunrise' 'United States Virgin Islands-2'
 'Great Britain-3' 'China-3' 'Ardilla' 'Danuta' 'Vim III' 'Ralia' 'Lasha'
 'Yugoslavia-2' 'Teresita' 'Hakahana' 'Glider' 'Jamaica-1' 'Rush V'
 'Legionario' 'Moorina' 'Vinha' 'Pan II' 'Squid III' 'Mexico-2'
 'Singapore-1' 'Falcon IV' 'Argonaut Rowing Club' 'Serbia-1' 'Kannibaltje'
 'Belgium-1' 'New York Athletic Club-1' 'New York Athletic Club #2-4'
 'Salinero' 'Sjovinge' 'Nephos I' 'Satchmo' 'Luxembourg-1' 'Solos Carex'
 'England-1' 'Whirlaway' 'Dow Jones' 'Israel-2' 'Digby'] unique values

NOC:
 ['CHN' 'NED' 'USA' 'FIN' 'NOR' 'ROU' 'EST' 'FRA' 'ESP' 'EGY' 'BUL' 'ITA'
 'AZE' 'RUS' 'ARG' 'CUB' 'BLR' 'GRE' 'CMR' 'MEX' 'URS' 'NCA' 'HUN' 'NGR'
 'ALG' 'KUW' 'BRN' 'PAK' 'IRQ' 'LIB' 'QAT' 'MAS' 'IRI' 'CAN' 'IRL' 'AUS'
 'RSA' 'MAR' 'ERI' 'TAN' 'JOR' 'SUD' 'TUN' 'LBA' 'BEL' 'DJI' 'COM' 'KAZ'
 'BRU' 'KSA' 'MDV' 'ETH' 'INA' 'PHI' 'UZB' 'UAE' 'KGZ' 'TJK' 'EUN' 'JPN'
 'BRA' 'FRG' 'GDR' 'GER' 'ISR' 'SWE' 'ISV' 'TUR' 'SRI' 'ARM' 'CIV' 'KEN'
 'BEN' 'UKR' 'GHA' 'SOM' 'LAT' 'SYR' 'GBR' 'CHI' 'SUI' 'IND' 'POL' 'CRC'
 'PAN' 'GEO' 'SLO' 'CRO' 'GUY' 'POR' 'ANG' 'VEN' 'COL' 'BAN' 'PLE' 'PER'
 'URU' 'PUR' 'UGA' 'NZL' 'HON' 'ECU' 'TKM' 'MRI' 'TCH' 'SEY' 'MTN' 'CZE'
 'NIG' 'SKN' 'TTO' 'DOM' 'JAM' 'LBR' 'SUR' 'NEP' 'MGL' 'PLW' 'LTU' 'MON'
 'TOG' 'NAM' 'AHO' 'ISL' 'ASA' 'AUT' 'SAM' 'RWA' 'DMA' 'HAI' 'DEN' 'MLT'
 'LUX' 'CYP' 'GUI' 'ESA' 'BIZ' 'PAR' 'YMD' 'KOR' 'SGP' 'BER' 'SCG' 'SLE'
 'PNG' 'AFG' 'YEM' 'OMA' 'IOA' 'YAR' 'FIJ' 'VAN' 'MDA' 'YUG' 'BAH' 'GUA'
 'SRB' 'IVB' 'VIN' 'CAF' 'MAD' 'MAL' 'CHA' 'BIH' 'GUM' 'CAY' 'SVK' 'BAR'
 'GBS' 'THA' 'TLS' 'GAB' 'SMR' 'LAO' 'BOT' 'ROT' 'PRK' 'MOZ' 'SEN' 'CPV'
 'BOL' 'AND' 'ANT' 'ZIM' 'GRN' 'HKG' 'LCA' 'FSM' 'MYA' 'MAW' 'ZAM' 'COD'
 'RHO' 'MLI' 'TPE' 'STP' 'CGO' 'MKD' 'TGA' 'LIE' 'GEQ' 'MNE' 'SOL' 'ANZ'
 'COK' 'ALB' 'WIF' 'SWZ' 'BUR' 'BDI' 'ARU' 'NRU' 'VNM' 'GAM' 'CAM' 'BHU'
 'VIE' 'MHL' 'KIR' 'UAR' 'TUV' 'SAA' 'NFL' 'KOS' 'SSD' 'LES'] unique values

Season:
 ['Summer' 'Winter'] unique values

City:
 ['Barcelona' 'London' 'Calgary' 'Albertville' 'Lillehammer'
 'Salt Lake City' 'Lake Placid' 'Sydney' 'Atlanta' 'Sochi' 'Helsinki'
 'Nagano' 'Torino' 'Rio de Janeiro' 'Athina' 'Sarajevo' 'Mexico City'
 'Munich' 'Berlin' 'Melbourne' 'Roma' 'Antwerpen' 'Paris' 'Amsterdam'
 'Beijing' 'Montreal' 'Seoul' 'Moskva' 'Los Angeles' 'Tokyo' 'Vancouver'
 'Innsbruck' 'Grenoble' 'Sapporo' 'Chamonix' 'Stockholm'
 'Garmisch-Partenkirchen' 'Sankt Moritz' "Cortina d'Ampezzo"
 'Squaw Valley' 'Oslo' 'St. Louis'] unique values

Sport:
 ['Basketball' 'Judo' 'Speed Skating' 'Cross Country Skiing' 'Ice Hockey'
 'Badminton' 'Sailing' 'Biathlon' 'Gymnastics' 'Athletics' 'Alpine Skiing'
 'Weightlifting' 'Wrestling' 'Luge' 'Rowing' 'Bobsleigh' 'Swimming'
 'Football' 'Equestrianism' 'Shooting' 'Taekwondo' 'Boxing' 'Fencing'
 'Diving' 'Canoeing' 'Handball' 'Water Polo' 'Tennis' 'Cycling' 'Hockey'
 'Figure Skating' 'Softball' 'Archery' 'Volleyball'
 'Synchronized Swimming' 'Modern Pentathlon' 'Table Tennis'
 'Nordic Combined' 'Baseball' 'Rhythmic Gymnastics' 'Freestyle Skiing'
 'Rugby Sevens' 'Trampolining' 'Beach Volleyball' 'Triathlon'
 'Ski Jumping' 'Curling' 'Golf' 'Snowboarding' 'Short Track Speed Skating'
 'Skeleton' 'Rugby' 'Tug-Of-War' 'Art Competitions' 'Lacrosse'
 'Motorboating'] unique values

Event:
 ["Basketball Men's Basketball" "Judo Men's Extra-Lightweight"
 "Speed Skating Women's 500 metres" "Speed Skating Women's 1,000 metres"
 "Cross Country Skiing Men's 10 kilometres"
 "Cross Country Skiing Men's 50 kilometres"
 "Cross Country Skiing Men's 10/15 kilometres Pursuit"
 "Cross Country Skiing Men's 4 x 10 kilometres Relay"
 "Cross Country Skiing Men's 30 kilometres" "Ice Hockey Men's Ice Hockey"
 "Badminton Men's Singles" "Sailing Women's Windsurfer"
 "Biathlon Women's 7.5 kilometres Sprint"
 "Gymnastics Men's Individual All-Around"
 "Gymnastics Men's Team All-Around" "Gymnastics Men's Floor Exercise"
 "Gymnastics Men's Horse Vault" "Gymnastics Men's Parallel Bars"
 "Gymnastics Men's Horizontal Bar" "Gymnastics Men's Rings"
 "Gymnastics Men's Pommelled Horse" "Athletics Men's Shot Put"
 "Alpine Skiing Men's Downhill" "Alpine Skiing Men's Super G"
 "Alpine Skiing Men's Giant Slalom" "Alpine Skiing Men's Slalom"
 "Alpine Skiing Men's Combined" "Weightlifting Women's Super-Heavyweight"
 "Wrestling Men's Light-Heavyweight, Greco-Roman" "Luge Women's Singles"
 'Sailing Mixed Three Person Keelboat'
 "Rowing Men's Lightweight Double Sculls" "Athletics Men's Pole Vault"
 "Sailing Men's Two Person Dinghy" "Athletics Men's 1,500 metres"
 "Bobsleigh Men's Four" "Swimming Men's 100 metres Butterfly"
 "Swimming Men's 200 metres Butterfly"
 "Swimming Men's 4 x 100 metres Medley Relay" "Football Women's Football"
 'Equestrianism Mixed Jumping, Individual'
 "Cross Country Skiing Men's 15 kilometres"
 "Shooting Men's Rapid-Fire Pistol, 25 metres" "Shooting Men's Trap"
 "Athletics Men's 4 x 100 metres Relay" "Athletics Men's Long Jump"
 "Athletics Women's Javelin Throw"
 "Wrestling Men's Heavyweight, Freestyle" "Taekwondo Men's Flyweight"
 "Athletics Men's 5,000 metres" "Boxing Men's Light-Welterweight"
 "Weightlifting Men's Lightweight" "Weightlifting Men's Middleweight"
 "Football Men's Football" "Rowing Men's Coxless Pairs"
 "Fencing Men's epee, Individual" "Taekwondo Women's Flyweight"
 "Basketball Women's Basketball" "Diving Men's Platform"
 "Canoeing Men's Canadian Doubles, 500 metres"
 "Canoeing Men's Canadian Doubles, 1,000 metres"
 "Canoeing Men's Kayak Fours, 1,000 metres" "Handball Men's Handball"
 "Rowing Women's Coxless Pairs" "Boxing Men's Middleweight"
 "Water Polo Men's Water Polo" "Tennis Men's Doubles"
 "Wrestling Men's Featherweight, Freestyle"
 'Sailing Mixed Two Person Heavyweight Dinghy'
 "Athletics Women's Shot Put" "Cycling Women's Sprint"
 "Cycling Women's 500 metres Time Trial"
 "Athletics Men's 110 metres Hurdles" "Athletics Women's Marathon"
 "Athletics Men's 100 metres" "Athletics Men's High Jump"
 "Fencing Men's Foil, Individual" "Fencing Men's Foil, Team"
 "Fencing Men's Sabre, Team" "Boxing Men's Lightweight"
 "Boxing Men's Welterweight" "Rowing Men's Quadruple Sculls"
 "Rowing Men's Double Sculls" "Rowing Men's Coxed Pairs"
 "Rowing Men's Coxed Eights" "Athletics Men's 400 metres Hurdles"
 "Athletics Men's 400 metres" "Athletics Men's Hammer Throw"
 "Athletics Men's 800 metres" "Cycling Men's Road Race, Individual"
 "Swimming Men's 100 metres Freestyle" "Hockey Men's Hockey"
 "Alpine Skiing Women's Slalom" "Rowing Women's Single Sculls"
 "Swimming Men's 50 metres Freestyle"
 "Weightlifting Women's Featherweight" "Water Polo Women's Water Polo"
 "Handball Women's Handball" "Figure Skating Men's Singles"
 "Weightlifting Men's Heavyweight"
 'Equestrianism Mixed Three-Day Event, Individual'
 'Equestrianism Mixed Three-Day Event, Team' 'Figure Skating Mixed Team'
 "Sailing Women's Three Person Keelboat"
 "Cycling Women's Road Race, Individual" "Softball Women's Softball"
 "Archery Women's Individual" "Wrestling Men's Heavyweight, Greco-Roman"
 "Volleyball Men's Volleyball" "Synchronized Swimming Women's Duet"
 "Synchronized Swimming Women's Team" "Taekwondo Women's Featherweight"
 "Athletics Men's Marathon" "Athletics Men's 4 x 400 metres Relay"
 "Athletics Women's 3,000 metres" "Diving Women's Platform"
 "Shooting Men's Air Rifle, 10 metres" "Boxing Men's Featherweight"
 "Weightlifting Men's Flyweight"
 "Wrestling Men's Lightweight, Greco-Roman"
 "Wrestling Men's Super-Heavyweight, Greco-Roman"
 "Shooting Men's Free Pistol, 50 metres"
 "Shooting Men's Air Pistol, 10 metres" "Fencing Men's epee, Team"
 "Rowing Men's Coxless Fours" "Boxing Men's Light-Flyweight"
 "Boxing Men's Super-Heavyweight" "Shooting Women's Air Rifle, 10 metres"
 "Judo Men's Half-Middleweight" "Weightlifting Men's Light-Heavyweight"
 "Weightlifting Men's Middle-Heavyweight" "Athletics Men's Javelin Throw"
 "Volleyball Women's Volleyball"
 "Wrestling Men's Welterweight, Greco-Roman"
 "Wrestling Men's Middleweight, Greco-Roman"
 "Athletics Men's 10,000 metres"
 "Athletics Men's 3,000 metres Steeplechase"
 "Wrestling Men's Middleweight, Freestyle"
 "Swimming Women's 100 metres Backstroke"
 "Swimming Women's 200 metres Backstroke"
 "Swimming Women's 4 x 100 metres Medley Relay"
 "Wrestling Men's Light-Heavyweight, Freestyle"
 "Modern Pentathlon Men's Individual" "Modern Pentathlon Men's Team"
 "Athletics Women's 200 metres" "Table Tennis Women's Singles"
 "Table Tennis Women's Doubles" "Shooting Men's Skeet"
 "Athletics Men's 200 metres"
 "Shooting Men's Small-Bore Rifle, Three Positions, 50 metres"
 "Athletics Women's 100 metres" "Weightlifting Women's Lightweight"
 "Athletics Women's Long Jump" "Fencing Women's epee, Individual"
 "Swimming Men's 200 metres Freestyle"
 "Swimming Men's 4 x 100 metres Freestyle Relay"
 "Swimming Men's 4 x 200 metres Freestyle Relay"
 "Swimming Men's 200 metres Individual Medley"
 "Swimming Men's 400 metres Individual Medley" "Boxing Men's Heavyweight"
 "Wrestling Men's Bantamweight, Freestyle"
 "Wrestling Men's Flyweight, Freestyle" "Athletics Women's 5,000 metres"
 "Weightlifting Women's Light-Heavyweight"
 "Weightlifting Women's Heavyweight" "Athletics Men's Discus Throw"
 "Weightlifting Men's Featherweight" "Taekwondo Men's Featherweight"
 "Taekwondo Men's Welterweight" "Judo Men's Heavyweight"
 "Boxing Men's Bantamweight" "Bobsleigh Men's Two"
 "Wrestling Men's Lightweight, Freestyle" "Nordic Combined Men's Team"
 "Nordic Combined Men's Individual" "Baseball Men's Baseball"
 "Rowing Men's Coxed Fours" "Cycling Men's 100 kilometres Team Time Trial"
 "Boxing Men's Flyweight" "Fencing Men's Sabre, Individual"
 "Rhythmic Gymnastics Women's Group"
 "Gymnastics Women's Individual All-Around"
 "Gymnastics Women's Team All-Around" "Gymnastics Women's Floor Exercise"
 "Gymnastics Women's Horse Vault" "Gymnastics Women's Uneven Bars"
 "Gymnastics Women's Balance Beam" "Diving Women's Springboard"
 "Diving Women's Synchronized Springboard"
 "Athletics Women's 10,000 metres" "Athletics Men's Decathlon"
 "Athletics Women's 4 x 100 metres Relay" "Freestyle Skiing Men's Moguls"
 "Athletics Men's Triple Jump" "Swimming Women's 50 metres Freestyle"
 "Athletics Women's Discus Throw" "Athletics Women's 1,500 metres"
 "Shooting Women's Air Pistol, 10 metres"
 "Shooting Women's Sporting Pistol, 25 metres"
 "Canoeing Men's Kayak Doubles, 500 metres"
 "Canoeing Men's Kayak Singles, 500 metres"
 "Canoeing Men's Kayak Singles, 1,000 metres"
 "Shooting Men's Running Target, 50 metres"
 "Judo Women's Half-Heavyweight" "Athletics Women's Pole Vault"
 "Rugby Sevens Women's Rugby Sevens" "Table Tennis Men's Team"
 'Figure Skating Mixed Pairs' "Freestyle Skiing Men's Aerials"
 "Rowing Women's Coxed Eights" "Athletics Women's 4 x 400 metres Relay"
 "Swimming Men's 400 metres Freestyle"
 "Alpine Skiing Women's Giant Slalom" "Alpine Skiing Women's Super G"
 "Cycling Men's Sprint" "Cycling Men's 1,000 metres Time Trial"
 "Cycling Men's Individual Pursuit, 4,000 metres"
 "Wrestling Men's Welterweight, Freestyle"
 "Wrestling Men's Bantamweight, Greco-Roman"
 "Swimming Men's 100 metres Backstroke"
 "Rowing Women's Lightweight Double Sculls" "Athletics Women's 800 metres"
 "Rowing Women's Coxed Quadruple Sculls"
 "Biathlon Men's 10 kilometres Sprint"
 "Biathlon Men's 12.5 kilometres Pursuit" "Biathlon Men's 20 kilometres"
 "Biathlon Men's 4 x 7.5 kilometres Relay"
 'Biathlon Mixed 2 x 6 kilometres and 2 x 7.5 kilometres Relay'
 "Rhythmic Gymnastics Women's Individual"
 "Canoeing Men's Kayak Singles, Slalom" "Archery Men's Individual"
 "Archery Men's Team" "Swimming Women's 4 x 100 metres Freestyle Relay"
 "Speed Skating Women's 1,500 metres"
 "Speed Skating Women's Team Pursuit (6 laps)"
 "Cross Country Skiing Men's Sprint" "Athletics Women's 400 metres"
 "Speed Skating Men's 500 metres" "Speed Skating Men's 1,000 metres"
 "Trampolining Men's Individual" "Beach Volleyball Men's Beach Volleyball"
 "Cycling Women's Mountainbike, Cross-Country"
 "Triathlon Women's Olympic Distance"

Cree la matriz de características y el vector objetivo. 

Parta los datos en conjuntos de entrenamiento y prueba en una proporción 80/20.

Especifique, usando `ColumnTransformer` y `Pipeline`, el procesamiento que le va a realizar a los características de su modelo. Utilice `TargetEncoder` para codificar las variables de alta cardinalidad, mayor a 5.

In [67]:
#Eliminar valores con frecuencia menor o igual a 5.
Teams = df['Team'].value_counts().sort_values(ascending=False)
Teams

Team
United States       13662
France               7790
Canada               7639
Great Britain        7494
Italy                7412
                    ...
Greenoaks Dundee        1
Sunrise                 1
Dow Jones               1
Mexico-2                1
Digby                   1
Name: count, Length: 660, dtype: int64

Entrene un modelo de regresión lineal OLS. Reporte el error de entrenamiento y el error de prueba. Use RMSE como métrica de evaluación.

Reporte en una tabla los coeficientes asociados a cada característica del modelo.

Entrene un modelo Ridge. Sintonice  $\lambda$ por validación cruzada. Pruebe al menos 50 valores de  $\lambda$. 

Reporte el error promedio de validación cruzada, el valor de $\lambda$ sintonizado, el error de entrenamiento, y el error de prueba.

Reporte en una tabla los coeficientes asociados a cada característica del modelo.

Entrene un modelo Lasso. Sintonice  $\lambda$ por validación cruzada. Pruebe al menos 50 valores de  $\lambda$.

Reporte el error promedio de validación cruzada, el valor de $\lambda$ sintonizado, el error de entrenamiento, y el error de prueba.

Reporte en una tabla los coeficientes asociados a cada característica del modelo.

Use un modelo Lasso para hacer selección de características preservando únicamente 5 características en su modelo.

Con las características seleccionadas entrene nuevamente un modelo Ridge, sintonizando $\lambda$. 

Reporte el error promedio de validación cruzada, el valor de $\lambda$ sintonizado, el error de entrenamiento, y el error de prueba.

Reporte los coeficientes del modelo.